### ISSUE TITLE
error when I launch the code

### ISSUE THREAD

**Issue by axel584** [hlostam/srt2anki#2]
I have no idea to solve the problem : 

<code>(anki) ➜  srt2anki git:(main) ✗ python main.py ../Slam.WEBRip.Netflix.it\[cc\].srt                        
get_srt_df_cached
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
Loading Anki collection
Traceback (most recent call last):
  File "/home/axel/Dokumentujo/code/subtitle2anki/srt2anki/~/.virtualenvs/anki/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'word'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 63, in <module>
    main(sys.argv)
  File "main.py", line 47, in main
    anki_df = anki.get_anki_df(args.anki_path, language_short, args.card_deck)
  File "/home/axel/Dokumentujo/code/subtitle2anki/srt2anki/srt2anki/anki.py", line 28, in get_anki_df
    anki_df = analysis.lemmatise_spacy(anki_together, language_short)[['word']]
  File "/home/axel/Dokumentujo/code/subtitle2anki/srt2anki/srt2anki/analysis.py", line 53, in lemmatise_spacy
    lemmatised['word'] = lemmatised['word'].map(lambda x : x.replace(a,b))
  File "/home/axel/Dokumentujo/code/subtitle2anki/srt2anki/~/.virtualenvs/anki/lib/python3.8/site-packages/pandas/core/frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/axel/Dokumentujo/code/subtitle2anki/srt2anki/~/.virtualenvs/anki/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'word'
</code>

**Comment by axel584** [comment]
the problem seems to come from the fact that my anki was empty. It would be nice to be able to add a first movie to review with anki.
